#remote_theme: pages-themes/hacker@v0.2.0
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: CAMERON.EMAIL
description: Home of the Cameron's

show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
